### ISSUE TITLE
Scaffolder `pagination: false` doesn't work

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-graphql#110]
With this kind of scaffolding:

```yml
SilverStripe\GraphQL\Controller:
  schema:
    scaffolding:
      types:
        SilverStripe\Security\Member:
          fields: [ID, Name, FirstName, Surname, Email]
          nestedQueries:
            Groups:
              paginate: false
          operations:
            create: true
            read:
              paginate: false            
        SilverStripe\Security\Group:
          fields: [ID, Title, Description, Code]
          nestedQueries:
            Members:
              paginate: false
          operations:
            create: true
            read: true
```

The types are inferred correctly, but the queries return null values, so this doesn't wokr

```
{
  readMembers {
    ID
    Email
    Groups {
      ID
      Title
    }
  }
}
```
