### ISSUE TITLE
Anonymous access in the front end

### ISSUE THREAD

**Issue by nspyke** [silverstripe/silverstripe-graphql#147]
At present, there is no simple configuration interface to open the `graphql` endpoint up to the front end for anonymous access.

Due to config array merging, I'm not able to remove the `SilverStripe\GraphQL\Controller.Permissions[CMS_ADMIN]` key.

I've had to add this hack to my _config.php get it to work.
```
$rules = Config::inst()->get(Director::class, 'rules');
unset($rules['graphql']['Permissions']);
Config::modify()->set(Director::class, 'rules', $rules);
```
This probably opens me up to other issues, but if I don't enable CORS, I hoping it will be minimal.

I'm thinking there needs to be some sort of YML configuration to easily override the default behaviour and open it up.

**Comment by tractorcow** [comment]
You can either add a NEW route (i.e. don't use `/graphql` for public access, our recommendation) or you can reset permissions like this:

```yaml
---
Name: mygraphqlroutes
After: '#graphqlroutes'
---
SilverStripe\Control\Director:
  rules:
    graphql:
      Permissions: null
```
