### ISSUE TITLE
RFC: Multiple schema support

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#156]
## Introduction

This module supports only one schema, reachable (by default) on a single URL. This aligns with [GraphQL best practices](http://graphql.org/learn/best-practices/), which explain:

> GraphQL is typically served over HTTP via a single endpoint which expresses the full set of capabilities of the service. This is in contrast to REST APIs which expose a suite of URLs each of which expose a single resource. While GraphQL could be used alongside a suite of resource URLs, this can make it harder to use with tools like GraphiQL.

However, as this module matures, expands its install base in the community, and serves more areas of SilverStripe core, it is becoming increasingly clear that following this best practice is not in our best interest. Supporting multiple schemas would be a major benefit to both the core module suite as well as the prototypical consumer of this module (e.g. a developer of a decoupled app, or API as a service).

## The problem

In most installations of SilverStripe, users aren't just getting a framework. They're getting an application built on top of a framework. A single schema puts the concerns of applications built in the user space in direct conflict with all other GraphQL APIs in the system, which include not only SilverStripe core modules (e.g.`asset-admin`, `versioned-admin` at the time of this writing), but also any other thirdparty modules that may be using GraphQL to serve their data. With only a single endpoint, and a single schema, an application developer must colocate his or her own GraphQL API with everything else in the system, and this kind of burden is not only undue, but also a bad idea in general.

There are a few reasons why this forced colocation are concerning:

### 1) Performance
Each request to the GraphQL server generates a schema dynamically. As more types and operations are added to the single schema, the response time increases, approaching infinity, which doesn't scale. Performance bottlenecks like these expand the DDoS surface, which is particularly concerning for public graphql endpoints. We have yet to scratch the surface of caching the generated GraphQL schema, but we shouldn't mistake optimisation as a solution to an architectural problem.

### 2) Namespacing
Queries, Mutations, and Types all live in de facto global namespaces. Arranging the schema in any other way (e.g. `queryCMS { } queryMyApp { } mutationCMS { } ... etc.` would be a highly atypical breech of convention. To this end, the scaffolded types and operations are named with high verbosity in pursuit of uniqueness across the entire system. This uniqueness is never guaranteed, but it's highly reliable. The downside is more painful developer ergonomics. If the SilverStripe admin application was not sharing a space with the user, unique names would be easier to achieve, and the developer would more readily claim succinct and concise names without having to worry about what may already be in use.

### 3) Permissions

If a developers wants a public graphql API, right now they have no choice but to expose everything in the system. Having separate schemas would allow more granular permission structures, where admin APIs could be behind authentication and user defined APIs could be public.

### 4) Ergonomics

Tools like [GraphiQL](https://github.com/graphql/graphiql), as implemented in [silverstripe-graphql-devtools](https://github.com/silverstripe/silverstripe-graphql-devtools) provide a user-friendly sandbox to test queries and browse the GraphQL schema. When the schema is polluted with types and operations that are beyond the scope of the developer's application, they become less useful and more frustrating to use.

While SilverStripe is not unique in its offering of both a framework and application, it is a special case, and warrants a challenge to the single-schema design.

## Goals

A single-schema design is an assumption that is baked into various corners of the GraphQL module along with modules that rely on it. With this in mind, we should aim to:

* **Use composition and configuration whenever possible**. This will minimise API breakages, create more backward compatibility, and allow users to opt-in without more boilerplate code and skeletal class definitions.

* **Future proof against planned features**. A robust caching layer for schemas has yet to be actioned, but multiple schema support should nonetheless be built in a way that a caching layer can be implemented around it with little extra effort or knowledge.

* **Be client agnostic**. Users should be able to implement their own Apollo client, or whatever other library they choose without having to worry about idiosyncrasies of a SilverStripe GraphQL server. This is particularly relevant around the new [type caching](https://github.com/silverstripe/silverstripe-graphql/pull/154) work that supports the new version of Apollo.

## Proposal

Most of what is needed to support multiple schemas is already in place. We just need to codify and document how it should be done, as well as relocate and tidy up a few of the rough edges.

### 1) Abstraction of Manager

Right now, `Manager` is a concrete class definition. To support multiple schemas, we'll need to support multiple implementations of it. The best way to do this is to abstract it into a common interface, e.g:

```php
interface ManagerInterface
{
  public function getType($name): ObjectType;

  public function addType(ObjectType $type, $name = null): void;

  public function hasType($name): bool;

}
```

Implementations of multiple schemas then becomes:

```yaml
SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\ManagerInterface.admin
    class: SilverStripe\GraphQL\Manager
  SilverStripe\GraphQL\ManagerInterface.myapp
    class: SilverStripe\GraphQL\Manager
```

### 2) `Manager` becomes an explicit dependency of `SilverStripe\GraphQL\Controller`

Right now, the dependency between `Controller` and `Manager` is implicit. If a `Manager` instance is not available to the controller, it uses `Manager::createFromConfig()` and sets the result as an instance property. To support multiple schemas, the `Manager` instance will have to be an explicit dependency. This can be done through composition.

```yaml
  # ...
  SilverStripe\GraphQL\Controller.admin
    class: SilverStripe\GraphQL\Controller
    constructor:
      manager: %$SilverStripe\GraphQL\ManagerInterface.admin
  SilverStripe\GraphQL\Controller.myapp
    class: SilverStripe\GraphQL\Controller
    constructor:
      manager: %$SilverStripe\GraphQL\ManagerInterface.myapp
```

### 3) Support implementation-based config

One of the downsides of the configuration layer is that config structures must be attached to a concrete class definition (e.g. `SilverStripe\GraphQL\Controller`). In a multiple schema setup, config will have to be provided per implementation, not per class definition. Normally this would be done through`properties` or `constructor`, but those only accept scalar values and registered services.

The simplest workaround for this is to supply a `schemaKey` that maps to a known config location.

*vendor/silverstripe/admin/_config/graphql.yml*
```yaml
SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\ManagerInterface.admin
    class: SilverStripe\GraphQL\Manager
    properties:
      schemaKey: 'adminSchema'
SilverStripe\GraphQL\Manager:
  schemas:
    adminSchema:
      queries:
        # ...
      scaffolding:
        types:
           ## ...
```

*app/_config/graphql.yml*
```yaml
SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\ManagerInterface.myapp
    class: SilverStripe\GraphQL\Manager
    properties:
      schemaKey: 'myAppSchema'
SilverStripe\GraphQL\Manager:
  schemas:
    myAppSchema:
      queries:
        # ...
      scaffolding:
        types:
           ## ...
```

`ManagerInterface` would include a `setSchemaKey(string $key): void` method, and the class would load the schema using something like:

```
$this->configure($this->config()->get('schemas')[$this->schemaKey])
```

### 4) Routing

Implementations of `Controller` will have to be routed in `Director`.

*vendor/silverstripe/admin/_config/graphql.yml*
```yaml
SilverStripe\Core\Control\Director:
  rules:
    graphql:
      Controller: %$SilverStripe\GraphQL\Controller.admin
      Stage: Stage
      Permissions:
        CMS_ACCESS: CMS_ACCESS
```

*app/_config/graphql.yml*
```yaml
SilverStripe\Core\Control\Director:
  rules:
    my-graphql:
      Controller: %$SilverStripe\GraphQL\Controller.myapp
      Stage: Live
```

### 5) Caching

Existing and future caching mechanisms will rely on `schemaKey` for uniqueness. For instance, `assets/types.graphql` becomes `assets/myApp.types.graphql` and `assets/admin.types.graphql`.

## Further considerations

* It may be time to rename `Manager` to something more semantically useful, like `Schema` (and `SchemaInterface`). Granted, this might cause confusion with the `Schema` class offered by the `webonyx/graphql-php` module, but that shouldn't be a blocker. The GraphQL module also has a class named `Controller`. 

* `Manager` may not be the best repository for schema configurations. Maybe this would be a good use of `StaticSchema`?

* This raises questions about the lack of interdependency of `silverstripe/graphql` and `silverstripe/admin`. Because each can be used without the other, perhaps GraphQL should not work out of the box until configured. It should impose no opinions about where your schema is, what it is named, or what route it is on. If you're using GraphQL without admin, you should have to configure all of that. This leaves `silverstripe/admin` with the responsibility of configuring the "default" graphql schema that is status quo (when `moduleexists`, of course).

* The idea of providing a `schemaKey` is a workaround for a bigger limitation with `Config`. A more forward-thinking change might be to create a `ConfigurationProvider` interface in framework, and have `Manager` take that as a dependency rather than as an array.

```php
interface ConfigurationProvider
{
  public function getConfig(): array
}

class Manager implements ManagerInterface
{
  public function __construct(ConfigurationProvider $config);
}

// implementation
$manager = new Manager(
  new PathConfigurationFinder(Manager::class . '.schemas.myApp')
);
```

This would put users at liberty to store their configurations anywhere, or even define them procedurally if they wanted to.
