### ISSUE TITLE
Fix WithDescendants union type regression in scaffolding

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#215]
The docs say that you get `<type>WithDescendants`, but you don't. It's unclear when that happend, but it's a regression which versioned-admin and elemental now rely on. They can't just change their query to use descendant based logic, because that would force them to dynamically create those queries (based on the available types in a particular SilverStripe project).

We could fix this through the [https://github.com/silverstripe/silverstripe-graphql/issues/209](RFC: Replace "descendant unions" with fields to simplify querying), but that seems like a long time to leave this regression in the module.

This has also come up with devs on the #graphql channel just now

**Comment by chillu** [comment]
@unclecheese Just to minimise confusion here, could you validate my assumptions here?
- At some point in the past, `<typeWithDescendants>` worked, and was documented accordingly
- Then it broke, at least in 3.0.0
- versioned-admin and elemental started relying on this broken behaviour without unions
- We fixed this with https://github.com/silverstripe/silverstripe-graphql/pull/182
- Now versioned-admin and elemental are broken. And the only reason this isn't a widespread problem is because we haven't done a graphql 3.x stable release since https://github.com/silverstripe/silverstripe-graphql/pull/182

**Comment by chillu** [comment]
Workaround for this in https://github.com/open-sausages/silverstripe-graphql/commit/6dcc005b0178ae689967198dcf27cb5bbbae7d7c

**Comment by chillu** [comment]
Demo of the current issue in `3.0.1`:

graphql.yml

```yml
SilverStripe\Control\Director:
  rules:
    'graphql': '%$SilverStripe\GraphQL\Controller.default'
SilverStripe\GraphQL\Manager:
  schemas:
    default:
      scaffolding:
        types:
          Page:
            fields: '*'
            operations:
                read: true
           SilverStripe\ErrorPage\ErrorPage:
             fields: [ErrorCode]
```

```graphql
query readPages {
  readPages {
    edges {
      node {
       	Title
        ErrorCode
      }
    }
  }
}
```
Response

```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field \"ErrorCode\" on type \"Page\".",
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ]
    }
  ]
}
```

**Comment by chillu** [comment]
This doesn't work either

graphql.yml

```yml
SilverStripe\Control\Director:
  rules:
    'graphql': '%$SilverStripe\GraphQL\Controller.default'
SilverStripe\GraphQL\Manager:
  schemas:
    default:
      scaffolding:
        types:
          Page:
            fields: [Title,ErrorCode]
            operations:
              read: true
          SilverStripe\ErrorPage\ErrorPage:
            fields: [ErrorCode]
```

Response

```json
{
  "errors": [
    {
      "message": "Invalid field \"ErrorCode\" on Page",
      "code": 0,
      "file": 
```
