### ISSUE TITLE
"No array of fields defined" shows even when nestedQueries adds fields

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#216]
This should be a valid definition (scaffolded query returns fields), but it fails:

```yml
SilverStripe\GraphQL\Manager:
  schemas:
    default:
        scaffolding:
            MyModel:
              fields: []
              nestedQueries:
                MyRelationship: true
```

# PR's

- [x] https://github.com/silverstripe/silverstripe-graphql/pull/233
