### ISSUE TITLE
GraphQL 4: Nested queries should inherit the root query plugins

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#277]
Right now, nested queries (e.g. has_many, many_many) aren't first-class citizens. They should be true model queries that inherit the plugins of the model operations, e.g. sort, filter, paginate, etc. Probably not versioned?

**Comment by chillu** [comment]
> Probably not versioned?

I would say they are forced to inherit that context from the root query, otherwise it's going to be edge case central.

**Comment by unclecheese** [comment]
Interesting, OK, that would make things easier. I think versioned is implicit, anyway? Like if you specify a stage in the root query, you're setting a dataQuery param that's going to affect the nested queries..

**Comment by chillu** [comment]
Yep, it's explicit in terms of query data (important for cache keys), but implicit in terms of the ORM execution context inside that. Just thinking through the types a bit, this won't lead to more types or input types, right? Roughly speaking:

```graphql
type query {
  getPages(showInMenus:Boolean, stage:VersionedStageInputType): [Page]
}
type Page {
  children(showInMenus:Boolean): [Page]
  Version: Int
  IsPublished: True
}
```

**Comment by unclecheese** [comment]
It _can_ lead to more input types. Here:

```
Page:
 operations: { read: true} # PageFilterInputType
Blog:
  operations: { read: true } #BlogFilterInputType
  fields:
    relatedPages: true # Inherits the filter plugin. Will use existing PageFilterInputType
```

But, if I customise the fields I want, that changes things:

```
Page:
 operations: { read: true} # PageFilterInputType
Blog:
  operations: { read: true } #BlogFilterInputType
  fields:
    relatedPages:
      plugins:
        filter:
          fields:
            title: true # ReadBlogsRelatedPagesFilterInputType
```
