### ISSUE TITLE
Connection types are lowercased

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#284]
Types in GraphQL Type Language should be upper camel, which we follow for actual types created through `model`, e.g. `SiteTree`. But that's not the case for 

```
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        SilverStripe\CMS\Model\SiteTree:
          fields: '*'
          operations: '*'
```

Creates types `readSiteTreesConnection` and `readSiteTreesEdge`
