### ISSUE TITLE
Remove getPageByLink from default schema

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#285]
The cms module adds the following GraphQL config:

```
---
Name: cms-graphql
Only:
  classexists: 'SilverStripe\GraphQL\Schema\Schema'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\Schema\Registry\ResolverRegistry:
    constructor:
      cmsResolver: '%$SilverStripe\CMS\GraphQL\Resolver'
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    admin:
      ...
    default:
      queries:
        getPageByLink:
          model: SilverStripe\CMS\Model\SiteTree
          args:
            link:
              type: String!
              description: The link to the page, without the base URL, e.g. "path/to/page"

```

We instruct people to start developing their own schema in the `default` namespace. The docs don't mention that this is not a "blank slate". On the first schema build, I was surprised how slow it was given I only added a single (custom) model type, until I figured out that it's actually building the whole kitchen sink due to the `getPageByLink` defaults in the `cms` module. 

Option A: Make `getPageByLink` obsolete by allowing a new `Link` filter in scaffolded `readOneSiteTree()` queries
Option B: Document `getPageByLink` as an opt-in, with default config you can copy paste into your schema
Option C: Add `getPageByLink` to the `admin` schema instead, and allow users to pick and choose for their `default` schema
Option D: Create a mechanism by which modules can declare their "default GraphQL config" which you can bulk import into your schema

In my view, the `admin` schema should over time become the "content API" which effectively exposes the whole data model. Because we'll also need that build a React-based CMS. And for most decoupled publishing cases (e.g. Gatsby) you'd use that schema. But when you build custom apps, you want a much smaller API surface, either for security/performance reasons, or because you're actually making API commitments to third parties.
