### ISSUE TITLE
Schema level default_plugins?

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#289]
Many schema use cases outside of the CMS will have no need for versioning, or all the overhead it creates with type generations, as well as the additional security surface. There's currently no way to disable that *per schema*, just on an operation creator level (across schemas), or for a specific operation. This leads to verbose schemas like this:

```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        Page:
          fields: '*'
          operations:
            read:
              plugins:
                inheritance: false
                versioning: false
                readVersion: false
              readOne:
                plugins:
                  inheritance: false
                  versioning: false
                  readVersion: false
```

**Comment by unclecheese** [comment]
I think you would want:

```
SilverStripe\GraphQL\Schema\DataObject\ReadCreator:
  default_plugins:
    readVersion: false
```

**Comment by chillu** [comment]
Yeah but this would disable it for *all* schemas, which is basically not practical as it would break most CMS UI use cases. It needs to be schema specific to avoid the repetition I've illustrated above.

**Comment by unclecheese** [comment]
Oh, right I see. Yeah this will have to become part of the schema config. That's good. We're moving more stuff into "flushless" :-)

**Comment by unclecheese** [comment]
This is tricky. I think we should get rid of all `default_plugins` config settings -- model, operation, anywhere else, and we'll add a new `defaults` section to Schema.

```yaml
defaults:
  operations:
    read:
      plugins:
        filter: true
  models:
    SilverStripe\GraphQL\DataObject\DataObjectModel:
      plugins:
        inheritance: true
```

This would follow the same "flushless" pattern as everything else. You could put it in `defaults.yml` and have it magically added to the right place, or just do a generic `schema.yml` and add a `defaults` section as above.

**Comment by unclecheese** [comment]
Got rid of `default_plugins`, added new `defaults` section.

https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/62f049225c6655a7fff5bbc4a69e922d0b22c063
https://github.com/silverstripe/silverstripe-versioned/pull/293/commits/11f2f11221781ee20003e3ff5117e4b1e75023c8
https://github.com/silverstripe/silverstripe-admin/pull/1088/commits/3bd5ce9aa5c72d225b34e9cd724b012c2f5ea330
https://github.com/silverstripe/silverstripe-framework/pull/9652/commits/0d92d7767513d3451a45550deabc6377d7c47104

**Comment by unclecheese** [comment]
Have commented out nested plugins for now, because there's another issue open for that, and it needs to be dealt with in its own way.

**Comment by chillu** [comment]
Hmmm I still can't get `VersionedInputType` to disappear on my schema - what am I doing wrong?

```yml
---
Name: graphql-my-schema
After:
    - '*'
---
SilverStripe\Control\Director:
  rules:
    'graphql': '%$SilverStripe\GraphQL\Controller.default'

SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      defaults:
        operations:
          read:
            plugins:
              readVersion: false
          readOne:
            plugins:
              readVersion: false
        models:
          DataObject:
            plugins:
              versioning: false
              inheritance: false
      models:
        Page:
          fields:
            title: true
            content: true
          operations:
            read: true
            create:
              fields:
                - title
                - content
```

Also, in your previous comment you mention `SilverStripe\GraphQL\DataObject\DataObjectModel`, but the docs you added have that keyed to `DataObject` - is the comment outdated? I see the same (unexpected) inclusion of `VersionedInputType` on both variations.

**Comment by unclecheese** [comment]
Shoot, this might be an order of execution issue. I only tested it in a flushless scenario (e.g. _graphql/defaults.yml). I'm wondering if the admin/defaults.yml is taking priority over your config defintition.

**Comment by unclecheese** [comment]
Ah, nope, I see admin does it in standard config, so this should work.

**Comment by unclecheese** [comment]
Have replicated. Appears to be a regression from one of my other contemporaneous fixes. :)

**Comment by unclecheese** [comment]
Actually, I take that back . I had an override in my app config that was overriding the default, so I can't replicate. 

Any way you can test it here, so we're on the same page? https://github.com/unclecheese/schemageddon

(includes an sspak)

One issue I had, FWIW is that I had query caching enabled, which was caching the introspection query in GraphiQL. Not sure if you were testing that out or not, but it's a major footgun.

**Comment by chillu** [comment]
OK same issue on the schemageddon repo with the following config in `app/_config/ingo-test.yml`

```yml
---
Name: graphql-my-schema
After:
    - '*'
---
SilverStripe\Control\Director:
  rules:
    'ingo-test/graphql': '%$SilverStripe\GraphQL\Controller.ingo-test'

SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\Controller.ingo-test:
    class: SilverStripe\GraphQL\Controller
    constructor:
      schema: ingo-test

SilverStripe\GraphQL\Schema\Schema:
  schemas:
    ingo-test:
      defaults:
        operations:
          read:
            plugins:
              readVersion: false
          readOne:
            plugins:
              readVersion: false
        models:
          DataObject:
            plugins:
              versioning: false
              inheritance: false
      models:
        Page:
          fields:
            title: true
            content: true
          operations:
            read: true
            create:
              fields:
                - title
                - content
```
