### ISSUE TITLE
Throw on invalid plugin scope

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#291]
I think that's going to be really important given that rebuilds take so long, and it's a bit counter intuitive on which level plugins apply.

```
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        Page:
          fields: '*'
          plugins:
            inheritance: false <= works
          operations:
            read:
              plugins:
                inheritance: false  <= should throw
```

**Comment by unclecheese** [comment]
In that example, if `inheritance` was `true`, it would throw, right? I think this is the difference between a config level validation versus a validation when the schema is actually built. Because anything that's `false` in the list of plugins (or any other list in the config for that matter) is just going to be skipped over.

Seems like you might be looking for the validation to happen here: https://github.com/unclecheese/silverstripe-graphql/blob/pulls/master/schemageddon/src/Schema/Plugin/PluginConsumer.php#L79

**Comment by chillu** [comment]
Oh right, it ignores false plugins - which makes sense, faster execution. But it also doesn't throw with `inheritance: true`

```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        Page:
          fields: '*'
          operations:
            read:
              plugins:
                versioning: false
                readVersion: false
                inheritance: true
```
