### ISSUE TITLE
To disable model plugin, you need to set it on all models in an inheritance chain

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#292]
```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        SilverStripe\CMS\Model\SiteTree:
          plugins:
            inheritance: false
        Page:
          fields: '*'
          plugins:
            inheritance: false
          operations:
            read: true
```

Because of `default_plugins`, the `SiteTree` parent class and a potential `MyPage` subclass need to have `inheritance: false` as well. Maybe that's the intended effect? Actually, even with the `SiteTree` config above I wasn't able to get rid of the `Page.__extends` field. Aside: I'm favouring the "page" model as a baseline because it feels more natural, and is more readable than `readSiteTrees()`.

**Comment by unclecheese** [comment]
The last bit is due to a related bug fixed here https://github.com/unclecheese/silverstripe-graphql/commit/80cf697baa19d22dfa7300fdc46071190ea34643

The rest of this is a bit of a recursive problem. How should inheritance affect plugins if inheritance itself is a plugin?

This stuff is hard.

**Comment by unclecheese** [comment]
I present to you, the InheritedPlugins plugin.

https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/ce62cd3479941f5073e7552ec51f60aee4df13b8
https://github.com/silverstripe/silverstripe-admin/pull/1088/commits/9c7c3caaa6fc3dbc1c6f82cbc996a5fb4588b936
https://github.com/silverstripe/silverstripe-framework/pull/9652/commits/747c8eb95e65b0c9c7125548aa1e6df793bbc6f7

**Comment by chillu** [comment]
Hmm now I can't get `__extends` to show any more?

```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        Page:
          fields:
            title: true
            content: true
          operations:
            read: true
            create:
              fields:
                - title
                - content
        SilverStripe\CMS\Model\RedirectorPage:
          fields:
            externalUrl: true
```
