### ISSUE TITLE
Expose fields on inheritance model, but also limit to fields on this subclass

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#295]
The current "Nested type definitions" docs say:

> By exposing Page, we implicitly expose all of its ancestors and all of its descendants. Adding Page to our schema implies that we also want its parent SiteTree in the schema (after all, that's where most of its fields come from), but we also need to be mindful that queries for page will return descendants of Page, as well.
> But these types are implicitly added to the schema, what are their fields?
> The answer is only the fields you've already opted into. Parent classes will apply the fields exposed by their descendants, and descendant classes will only expose their ancestors' exposed fields.

This makes applying the `inheritance` plugin by default a bit ineffective, since you just get a bunch of "sub types" for model subclasses with exactly the same fields. My view is that if you say `fields:*` on the model, and have inheritance enabled, the logic should behave consistently between the base type and any sub types. Unless you explicitly limit the fields

```
> SiteTree
  > Page
    > NewsPage
    > Contact Page
```

```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        Page:
          fields: '*'
          operations: '*'
        MyProject\Pages\NewsPage:
          fields:
            publishDate: true
```

This would result in all fields exposed on `Page` and `ContactPage`, but only the `publishDate` field on `NewsPage`

Also, I think we should only expose fields on this actual subclass within `__expose`. I get the point about making it easier to destructure frontend code, but I don't think it's a strong enough reason to bloat both the schema generation and DX.
