### ISSUE TITLE
__extend should only be exposed on the base type

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#296]
I think it's overkill to model the entire hierarchy in nested extends.

Current types:

```graphql
type Page {
  __extends: PageDescendants
}
type MyPage {
  __extends: MyPageDescendants
}
type MySubPage {
  __extends: MyPageDescendants
}
type PageDescendants = MyPage
type MyPageDescendants = MySubPage
```

Proposed types:

```graphql
type Page {
  __extends: PageDescendants
}
type MyPage {
}
type MySubPage {
}
type PageDescendants = MyPage | MySubPage
```

**Comment by unclecheese** [comment]
This was a pretty big change. Can you have a play with it and see if it's matching the above expectations?

https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/6a97f7b1add3df6715ebe26ae902a0676cc8e7c5

https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/d2f3bf5433fcfc53658e30f383122c26b13b5627

What you should see:

* `_extend` only on base class
* On the `_extend` "pseudo union", only expose native, explicitly exposed fields, or fields with custom names

```yaml
SiteTree:
  fields: '*'
Page:
  operations:
    read: true
```

No `__extend` field. `Page` has no explicitly exposed fields.

```yaml
SiteTree:
  fields: '*'
Page:
  operations:
    read: true
  fields:
    title: true
    myPageField: true
```

SiteTree now has an `__extend` field. Only property is `page`, with a `myPageField` field. `title` is filtered out because it's not native.

```graphql
query readSiteTrees {
  nodes {
    title
    __extend {
      page {
        myPageField
      }
    }
  }
}
```

However, `title` is still available on a regular page read:

```graphql
query readPages {
  nodes {
    title
  }
}
```


```yaml
SiteTree:
  fields: '*'
Page:
  fields:
    title: true
    myPageField: true
    commentCount:
      type: Int
      property: 'Comments.Count()'
RedirectorPage:
  fields:
    redirectionType: true
```

The `page` field on `__extend` now includes the custom property, and `redirectorPage` is included.

```graphql
query readSiteTrees {
  nodes {
    title
    __extend {
      page {
        myPageField
        commentCount
      }
      redirectorPage {
        redirectionType
      }
    }
  }
}
```

**Comment by chillu** [comment]
Awesome job! But I think this broke fields in the return type - in the `default` schema in schemageddon, the `Page` type no longer has `content` and `title` fields, even though it includes all fields via `_graphql/default/models/sitetree.yml`. 

This doesn't seem to extend to versioning? The config below leads to a `PageVersion` type which is missing the `title` and `content` fields. Might be the same issue?

And I think this broke inheritance - I expected to get a `Page.__extends` field because I included `RedirectorPage.ExternalURL`, but I didn't (on my own schema):

```yml
---
Name: graphql-my-schema
After:
    - '*'
---
SilverStripe\Control\Director:
  rules:
    'ingo-test/graphql': '%$SilverStripe\GraphQL\Controller.ingo-test'

SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\Controller.ingo-test:
    class: SilverStripe\GraphQL\Controller
    constructor:
      schema: ingo-test

SilverStripe\GraphQL\Schema\Schema:
  schemas:
    ingo-test:
      defaults:
        operations:
          read:
            plugins:
              readVersion: true
          readOne:
            plugins:
              readVersion: true
        models:
          DataObject:
            plugins:
              versioning: true
              inheritance: true
      models:
        SilverStripe\CMS\Model\SiteTree:
          fields: '*'
        Page:
          fields:
            subHeading: true
          operations:
            read: true
            create:
              fields:
                - title
                - content
                - subHeading
        SilverStripe\CMS\Model\RedirectorPage:
          fields:
            externalUrl: true
```
