### ISSUE TITLE
Operations require "fields" as values, everything else as keys

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#299]
```yml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        Page:
          fields:
            title: true
            content: true
          operations:
            read: true
            create:
              fields:
                title: true
                content: true
```

Results in:

```
Uncaught Exception Error: "Call to a member function getType() on null" at /app/vendor/silverstripe/graphql/src/Schema/DataObject/CreateCreator.php line 117
```

It requires this syntax instead:

```yml
operations:
  read: true
  create:
    fields:
      - title
      - content
```

The notation should be consistent, and we should throw a schema validation error if you try to use array value notation (or start supporting it everywhere). Note that this also extends to `exclude` fields.
