### ISSUE TITLE
Nested filter fields don't work

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#307]
Running the following schema in the [schemageddon](https://github.com/unclecheese/schemageddon) "testing" schema:

```yml
models:
  UncleCheese\MyProject\DataObjects\Product:
    fields: '*'
    operations:
      read:
        plugins:
          filter:
            fields:
              title: true
              primaryCategory:
                title: true
```

Query:

```graphql
query {
  readProducts(filter:{primaryCategory: {title:{contains:"Revolutionize"}}}) {
    id
  }
}
```

Error:

```
primaryCategory is not a relation on model UncleCheese\\MyProject\\DataObjects\\Product"
```

Note that if I change that to the same upper camel case as the ORM declaration (`PrimaryCategory`) I get a different error:

```
Couldn't run query:\n\nSELECT DISTINCT \"Product_Live\".\"ClassName\", \"Product_Live\".\"LastEdited\", \"Product_Live\".\"Created\", \"Product_Live\".\"Version\", \"Product_Live\".\"Title\", \"Product_Live\".\"Description\", \"Product_Live\".\"Price\", \"Product_Live\".\"OnSale\", \"Product_Live\".\"InStock\", \"Product_Live\".\"FeaturedImageID\", \"Product_Live\".\"PrimaryCategoryID\", \"Product_Live\".\"ID\", \n\t\t\tCASE WHEN \"Product_Live\".\"ClassName\" IS NOT NULL THEN \"Product_Live\".\"ClassName\"\n\t\t\tELSE 'UncleCheese\\\\MyProject\\\\DataObjects\\\\Product' END AS \"RecordClassName\"\n\nFROM \"Product_Live\"\nLEFT JOIN \"Category\" AS \"primarycategory_Category\" ON \"primarycategory_Category\".\"ID\" = \"Product_Live\".\"PrimaryCategoryID\"\n\nWHERE (\"PrimaryCategory\".\"title\" LIKE ?)\n\nORDER BY \"Product_Live\".\"ID\" ASC\n\n42S22-1054: Unknown column 'PrimaryCategory.title' in 'where clause'"
```

Maybe we just remove the ability to filter nested fields for now, and mark it as an enhancement for later? We'd need to update the docs since they mention it.

**Comment by unclecheese** [comment]
This either needs to be a WONTFIX, and we get rid of this option, or we need to document some serious limitations to this API. Here's the deal:

Types can appear in various contexts, at different levels of nesting, and their filter input types apply in all those places. So you may have:

```
query  {
  readProductReviews({ filter: { content... , rating, product:  <Nested input type >}) {
  }

  readProducts({ filter: { price, title... reviews <Nested input type>})  {

  }
}
```

The `NestedInputTypeBuilder` is quite conservative, and it doesn't just assume the input type for `product` on `readProductReviews` will be distinct from the input type for `readProducts(filter: ProductFilterInputType)`.

In most cases, the input type is the same in all contexts, which creates a lot of schema bloat. Additionally, giving them all distinct names becomes really cumbersome. 

Therefore, the rule is, you get to declare `fields` once to customise the input type, but if the type needs to generate an input type later on in some other context, and the fields aren't defined, it will just assume `*` (all exposed fields), because it's undefined, and merge it in, meaning you're not likely to end up with a customised input type for any object that has relationships, provided those related objects are also exposed.

I really don't see a strong use case for customising the input type. If you've exposed the fields for reading, I don't know why you would be stingy about filtering on them.

Will wait for feedback from @chillu on this one, but I'm leaning toward closing it and making a note in the documentation.

**Comment by chillu** [comment]
>  If you've exposed the fields for reading, I don't know why you would be stingy about filtering on them.

Some fields can be pretty expensive to query, especially on `contains` with large amounts of `TEXT` column data, or if the relationship has expensive join operations (worst case: in memory). And it's just a bit more complexity to deal with in terms of the API surface that some devs will be keen to avoid. 

I can't think of business level reasons why you'd want to limit filter fields which are exposed in `read` queries already, because you could just perform the same filters after retrieving the full data set (it doesn't expose any new data or metadata).

> In most cases, the input type is the same in all contexts, so assuming distinct would create a lot of schema bloat. Additionally, giving them all distinct names becomes really cumbersome.

Yeah let's not do that. Could we simply throw a build exception if you have two filter definitions for the same type with different nested fields?

```yml
# Product has many Category
models:
  Product:
    fields: '*'
    operations:
      read:
        plugins:
          filter:
            fields:
              title: true
              # Creates ProductCategoryFilterInput
              category:
                title: true
  Category:
    fields: '*'
    operations:
      read:
        plugins:
          filter:
            # Reuses ProductCategoryFilterInput
            fields:
              title: true
              # Throws
              otherField: true
```
