### ISSUE TITLE
Don't half set up "default" schema

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#317]
I've skimmed the [intro docs](https://docs.silverstripe.org/en/4/developer_guides/graphql/getting_started/activating_the_server/) to set up a `default` schema, and had assumed this also required setting up the controller injection.

```yml
SilverStripe\Control\Director:
  rules:
    'graphql': '%$SilverStripe\GraphQL\Controller.default'
SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\Controller.default:
    class: SilverStripe\GraphQL\Controller
    constructor:
      schemaKey: default
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
```

Turns out there's a [schema-default.yml](https://github.com/silverstripe/silverstripe-graphql/blob/master/_config/schema-default.yml) which sets up that particular schema, but requires "activation" through a Director rule. It also sets up slightly different defaults than [schema-global.yml](https://github.com/silverstripe/silverstripe-graphql/blob/master/_config/schema-global.yml). 

This results in fun config YAML merging behaviour where the constructor args are merged into `[default, default]`, which then breaks PHP type hinting in an unhelpful way.

```
[Emergency] Uncaught TypeError: Argument 2 passed to SilverStripe\GraphQL\Controller::__construct() must implement interface SilverStripe\GraphQL\QueryHandler\QueryHandlerInterface or be null, string given
```

I think we should stick to `schema-global` definitions, and then ask beginners to copy and paste a bit more YAML config. This actually increases the visibility of some settings, e.g. the middlewares applied via `middlewares.yml` to this particular schema key, and will quite likely be missed by anyone setting up a schema under a different key.
