### ISSUE TITLE
GraphQL 4: filter fields include custom getters

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#334]
```
Page: 
  fields:
    '*': true
    link: true
```

Should omit "link" because it is not queryable.
