### ISSUE TITLE
Validate "src" is an array, prevent it from building

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#370]
```yaml
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      src:
        'app/_graphql/default'
```

This config will work, *until* you install a module like `unclecheese/elemental-unions` which adds its own `src` key as an array, in which case the schema will stop building.
