### ISSUE TITLE
[v4] Error when querying enum fields

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-graphql#417]
> Uncaught Error: Call to undefined method SSGraphQLSchema_c21f969b5f03d33d43e04f8f136e7682\Types::QueryFilterDimensionsEnumComparator()

This is called from generated code, specifically the `<model>FilterFields` class. Looks like it is generated by this method:

https://github.com/silverstripe/silverstripe-graphql/blob/b11582a84b5920887cf5d5091c00d35635701bde/src/Schema/Plugin/AbstractQueryFilterPlugin.php#L113-L120

Model/config is very simple:

```php
<?php

namespace App\Model\Products;

class Product extends DataObject
{
    private static $table_name = 'Product';

    private static $db = [
        'Title' => 'Varchar(255)',
        'Dimensions' => 'Enum(array("2D", "3D"), "2D")',
    ];
}
```

```yml
App\Model\Products\Product:
  fields:
    id: true
    title: true
    dimensions: true
  operations:
    read: true
```

<details>
<summary>_graphql/config.yml, in case it’s relevant</summary>

```yml
modelConfig:
  DataObject:
    plugins:
      versioning: false
    operations:
      read:
        plugins:
          readVersion: false
      readOne:
        plugins:
          readVersion: false
      delete:
        plugins:
          unpublishOnDelete: false
```
</details>

Build runs fine, but as soon as the `readProducts` query is run the above error occurs
