### ISSUE TITLE
GraphQL 4 : QueryFilter and Paginator plugins not working together?

### ISSUE THREAD

**Issue by priyashantha** [silverstripe/silverstripe-graphql#440]
Wnen the filter and paginatedList plugins added to the read operation only paginatedList gets applied. There is no query argument for `filter`. But when paginatedList disabled explicitly and filter enabled then `filter` argument gets applied

**Comment by priyashantha** [comment]
Actually, I found how that can be done, just needed to use `before`

```
operations:
    read:
      plugins:
        filter:
          before: paginateList
```

So closing this issue
