### ISSUE TITLE
"On demand" schema generation doesn't occur if schema has changed

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-graphql#459]
# Problem
If there's a pre-existing schema built and your schema definition changes, on-demand build won't notice and rebuild itself.

# Steps to reproduce
- Create this schema definition with the matching object
- Run a graphql query. This will auto build the schema on demand.
- Update the schema to remove the boom field
- Rerun the query.

Expected results: Query should complain that the boom field doesn't exist.
Actual results: Query succeeds.

```yml
---
Name: myppojectgraphql
After: '#graphqlconfig'
---
SilverStripe\Control\Director:
  rules:
    'graphql': '%$SilverStripe\GraphQL\Controller.default'

SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      models:
        Dummy:
          operations: '*'
          fields:
            id: true
            boom: true
```

```graphql
{
  readDummies {
    nodes {
      id
      boom
    }
  }
}
```
