### ISSUE TITLE
Query override error 

### ISSUE THREAD

**Issue by Zeeshanjbd2** [silverstripe/silverstripe-graphql#471]
I have a query in one of my vendor package folder 
```
'readAddresss':
  type: '[Address]'
  args:
    MemberID: ID
    limit: Int
    offset: Int
  resolver: [ 'XYZ\Core\Resolvers\ReadAddressResolver', 'resolveReadAddresss' ]
```

i want to override this query in my app 
```

'readAddresss':
  type: '[Address]'
  args:
    PurchasingUser: Boolean
    MemberID: ID
    limit: Int
    offset: Int
  resolver: [ 'App\Resolvers\AddressResolver','resolveReadAddresss' ]
```

But it throws error

[Emergency] Uncaught SilverStripe\GraphQL\Schema\Exception\SchemaBuilderException: Callable array ( 0 => 'App\\Resolvers\\AddressResolver', 1 => 'resolveReadAddresss', 2 => 'XYZ\\Core\\Resolvers\\ReadAddressResolver', 3 => 'resolveReadAddresss', ) provided to SilverStripe\GraphQL\Schema\Resolver\ResolverReference is not valid
