### ISSUE TITLE
filter plugin with enum fields leave unresovled reference in compiled schema php

### ISSUE THREAD

**Issue by MasonD** [silverstripe/silverstripe-graphql#484]
```php
class ClassWithEnum extends DataObject {
  public static $db = [ 'EnumField' => "Enum('OptionOne,OptionTwo','OptionOne')" ];
}
```

```yml
ClassWithEnum:
  fields:
    enumField: true
  operations:
    read: true
```

The compiled php code will contain a reference to Types::QueryFilterEnumFieldEnumComparator(), which does not exist.
