### ISSUE TITLE
[v4] Infinite loop with Injector replaced classes (subclass replacing parent class)

### ISSUE THREAD

**Issue by AljosaB** [silverstripe/silverstripe-graphql#524]
## Affected Version
SS 4.11+
GrapQl v4

## Steps to Reproduce
**/app/src/SomePage.php**
```php
<?php

namespace App\Pages;

use Page;

class SomePage extends Page
{
    
    private static $table_name = 'SomePage';

    private static $singular_name = 'SomePage';
    private static $description = 'SomePage';

    private static $db = [
        'SomeField' => 'Int'
    ];

}
```

**/app/src/PageExtendingSomePage.php**
```php
<?php

namespace App\Pages;

class PageExtendingSomePage extends SomePage
{
    public function NewFunction()
    {
        // do something
    }
}
```

**/app/_config/injectors.yml**
```yml
SilverStripe\Core\Injector\Injector:
  App\Pages\SomePage:
    class: App\Pages\PageExtendingSomePage
```

**/app/_config/graphql.yml**
```yml
SilverStripe\Control\Director:
  rules:
    'graphql': '%$SilverStripe\GraphQL\Controller.default'

SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      src:
        - app/_graphql
```

**/app/_graphql/models.yml**
```yml
App\Pages\SomePage:
  fields: '*'
  operations:
    read: true
```

**Run**
```bash
/vendor/silverstripe/framework$ php cli-script.php dev/graphql/build schema=default
```

**Error**
```
[INFO]: --- Building schema "default" ---
ERROR [Emergency]: Uncaught Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames at /vendor/silverstripe/framework/src/Core/Injector/SilverStripeServiceConfigurationLocator.php line 50
```

## Additional info
- it starts working the moment you comment out injectors.yml lines
- related ticket silverstripe/silverstripe-elemental#1014

## Acceptance criteria
- GraphQL schema models honour Injector overrides even for subclasses
- Schema builds complete successfully

## PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/549
