### ISSUE TITLE
NestedInputBuilder (sort and filter plugins) doesn't work with nested '*'

### ISSUE THREAD

**Issue by MasonD** [silverstripe/silverstripe-graphql#535]
If a sort plugin configuration is, say
```yml
plugins:
  sort:
    fields:
      id: true
      subQuery:
        '*': true
```
This does not work, because the relevant code in NestedInputBuilder is 
```php
        foreach ($fields as $fieldName => $data) {
            if ($fieldName === Schema::ALL) {
                $this->buildAllFieldsConfig($type);
            }
            if ($data === false) {
                continue;
            }
```
which computes and then immediately discards `buildAllFieldsConfig` for the nested type, doing absolutely nothing.

PR should be inc. soon

### PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/536
- https://github.com/silverstripe/silverstripe-graphql/pull/538

**Comment by GuySartorelli** [comment]
I'm not able to reproduce this issue.

Using the following graphql models schema:

```yml
SilverStripe\Security\Group:
  fields:
    '*': true

SilverStripe\Security\Permission:
  fields:
    id: true
    group: true
  operations:
    readOne: true
    read:
      plugins:
        sort:
          fields:
            id: true
            group:
              '*': true
```

and the following query:

```graphql
query getPerms {
  readPermissions(sort: {group: {title: DESC}}) {
    nodes {
      id
      group {
        id
        title
      }
    }
  }
}
```

I see the results being sorted appropriately. I have tested sorting by other group fields and changing the sort direction as well, and I get the expected resiults.

@MasonD When you say "This does not work", what specifically doesn't work?
- Are you shown an error?
  - if so, what are the steps to reproduce that, and what is the error?
- Or does something just not work exactly how you expect it?
  - if so, what are the steps to reproduce that, what is the expected behaviour, and what are you seeing instead?

**Comment by MasonD** [comment]
Oh, sorry, my bad. That does work. The issue only happens when nesting happens one level further, and including `readOne` **masks** the error because it's implicitly `sort: fields: '*'` which read then just extends.

For example with
```yaml
SilverStripe\Security\Group:
  fields:
    description: true
    sort: true
    members: true

SilverStripe\Security\Member:
  fields:
    id: true
    firstName: true
    surname: true

SilverStripe\Security\Permission:
  fields:
    id: true
    group: true
  operations:
    read:
      plugins:
        sort:
          fields:
            '*': false
            id: true
            group:
              id: true
              members:
                '*': true
```

you should encounter the error 
```
Uncaught SilverStripe\GraphQL\Schema\Exception\SchemaBuilderException: Failed to apply plugin SilverStripe\GraphQL\Schema\DataObject\Plugin\QuerySort to readPermissions. Got error "Could not find field "*" on type "Member". If it is a custom filter field, you will need to provide a
                resolver function in the "resolver" config for that field along with an explicit type."
```
