### ISSUE TITLE
Unable to disable CSRF Middleware

### ISSUE THREAD

**Issue by mkekit** [silverstripe/silverstripe-graphql#574]
### Module version(s) affected

5.1.3

### Description

Unfortunately i'm not able to disable the CSRF protection as mentioned in the [documentation](https://docs.silverstripe.org/en/5/developer_guides/graphql/security_and_best_practices/csrf_protection/#disabling-csrf-protection-for-token-based-authentication-only).
Here's the contents of my config under `app/_config/graphql.yml`:

```yml
---
Name: app-graphql
Only:
  classexists: 'SilverStripe\GraphQL\Schema\Schema'
After:
  - graphqlconfig
---
SilverStripe\GraphQL\Auth\Handler:
  authenticators:
    - class: SilverStripe\GraphQL\Auth\BasicAuthAuthenticator
      priority: 100

SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      src:
        - app/_graphql

SilverStripe\Core\Injector\Injector:
  SilverStripe\GraphQL\QueryHandler\QueryHandlerInterface.default:
    class: SilverStripe\GraphQL\QueryHandler\QueryHandler
    properties:
      Middlewares:
        csrf: false

```

Which leads to the following error:

```json
"errors": [
        {
            "message": "Mutations must provide a CSRF token in the X-CSRF-TOKEN header",
            "code": 0,
            "file": "/var/www/html/vendor/silverstripe/graphql/src/Middleware/CSRFMiddleware.php",
            "line": 26
       }
]
```
What i've missed here?

Thanks in advance!

### How to reproduce

* Add the above config
* Use a GraphQL Client
* Try to perform a GraphQL mutation

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by mkekit** [comment]
Hello, I found a solution for the problem/behavior. After adding 'graphql-middlewares' additionally as 'After' in my graphql.yml config, everything works now. Perhaps this should also be added to the documentation? 

Here's the updated configuration:

```yml
---
Name: app-graphql
Only:
  classexists: 'SilverStripe\GraphQL\Schema\Schema'
After:
  - graphqlconfig
  - 'graphql-middlewares'
---
...
```
