### ISSUE TITLE
Nested filtering issue

### ISSUE THREAD

**Issue by jackkemmish** [silverstripe/silverstripe-graphql#588]
### Module version(s) affected

5.2

### Description

Hi there,

I am trying to filter on a field which is part of a page type I have, but I am getting a an error e.g. `Failed to resolve field readOneResourcePage returning ResourcePageInterface.`.

I have seen this open ticket around nested filtering https://github.com/silverstripe/silverstripe-graphql/issues/307 but can also see in the docs I should be able to filter by default here `Nested fields are supported by default:` https://docs.silverstripe.org/en/5/developer_guides/graphql/working_with_dataobjects/query_plugins/

### How to reproduce

I am still very much in the learning stages here so I may be missing something, but here is my code (I have reduced it for the example):

Schema:
```yaml
models:
  Sdots\App\ResourcePage:
    fields:
      '*': true
      link:
        type: String
        property: Link
    operations:
      read: true
      readOne:
        plugins:
          getByLink: true
  Sdots\App\ResourceListPage:
    fields:
      '*': true
      link:
        type: String
        property: Link
    operations:
      read: true
      readOne:
        plugins:
          getByLink: true
  Sdots\Tagging\Model\TagGroup:
    fields: '*'
    operations:
      read: true
  Sdots\Tagging\Model\Tag:
    fields: '*'
    operations:
      read: true
```

I would assume that the above would allow me to filter by ID on the `tagGroup` or `tags` as it's exposed in the schema. I have also attached an image of the structure of the schema in the GraphQL IDE, and the error.

<img width="1728" alt="Screenshot 2024-05-18 at 21 01 28" src="https://github.com/silverstripe/silverstripe-graphql/assets/10498947/f750e3e8-153a-4b8f-9484-76a9fb90741a">
<img width="1728" alt="Screenshot 2024-05-18 at 21 02 12" src="https://github.com/silverstripe/silverstripe-graphql/assets/10498947/cb3b19f3-c131-458f-ab22-c9ed3ce91e1f">

I feel like I'm either missing something, or something is not working :/

Thanks in advance.

Jack

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)
