### ISSUE TITLE
Limit fields in input types for create and update operations

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#67]
@unclecheese has worked out two options:

1. Operation centric

```
types:
  BlogPost:
    fields: [Title, Content, Author]
    operations:
      read: true # all fields exposed
      create:
        fields: [Title, Content] # explicit whitelist of fields
      update:
        excludeFields: [Title] # explicit blacklist of fields, all other fields on type exposed implicitly
  Member:
    fields: [FirstName, Surname]
```

2. Field centric

```
types:
  BlogPost:
    fields:
      Title:
        description: The title field
        visibility: *
      Author:
        description: The author of the post
        visibility: read
      Content:
        description: The content of the post
        visibility: [read, update]
    operations:
      read: true
      create: true
  Member:
    fields: [FirstName, Surname]
```

**Comment by unclecheese** [comment]
I'm going to revise the example, because on second look, `read` should not be in there. The output of `read` is defined by the type itself. And needless do say, `delete` should be invalid, as well.

**Comment by unclecheese** [comment]
Additionally, we need to consider how these mutations will handle the exposure of the `Author` relationship. @sminnee and I worked out something like this:

```
types:
  BlogPost:
    fields: [Title, Content, Author] # AuthorID is now implicitly exposed
```

```
createPost($Input) { ... }

{
"Input": {
  "Title": "Some post title",
  "AuthorID": 5 <-- Use an existing author
}
}
```

```
createPost($Input) { ... }

{
"Input": {
  "Title": "Some post title",
  "Author": { "FirstName": "Uncle", "Surname": "Cheese" } <--- Creates a new author
}
}
```

```
createPost($Input) { ... }

{
"Input": {
  "Title": "Some post title",
  "Author": { "ID": 5, "FirstName": "Aunty", "Surname": "Crackers" } <--- Throws. ID is never mutable
}
}
```

```
createPost($Input) { ... }

{
"Input": {
  "Title": "Some post title",
  "AuthorID": 5,
  "Author": { "FirstName": "Aunty", "Surname": "Crackers" } <--- Creates post, updates Author.
}
}
```

**Comment by chillu** [comment]
I think nested creates/updates should be a separate ticket, let's start with allowing value assignment through a database ID. Same with has_many and many_many - separate ticket :)

**Comment by unclecheese** [comment]
OK, I'll draw that up now. :)

My preference is for defining the visibility at the operation level. I think the `fields` definition is getting a bit verbose and clunky. There are currently many shapes that the `fields` definition can take on:

* Enumerated list: `fields: [Title, Content]`
* Map: `fields: {Title: 'Some description', Content: 'Some other description'}
* String: `fields: *`
* And something completely different: `excludedFields: [Title]`

Adding `visibility` would force you into that Map definition, which is fine, but it means that the other styles are still kicking around with a questionable level of utility.

Operations, on the other hand, have a much leaner definition. This will be the first change that makes them configurable in any other way than on/off.

**Comment by chillu** [comment]
I'm fine with an operation centric approach, for the reasons you mentioned. How do you think we should handle excluding `ID` from `create`? If we set an `excludeFields` default, it would get overwritten by custom YAML config, and the implementor would have to remember to re-set the field. We could work with YAML anchor properties and list merges ([details](https://en.wikipedia.org/wiki/YAML#Advanced_components)), which means you need to remember to merge in the anchor property (and figure out its name). Either way, its prone to human error. Maybe a `defaultExcludeFields`?

> I'm going to revise the example, because on second look, read should not be in there. The output of read is defined by the type itself. 

Not sure what you mean by that - you should be able to control field visibility on `read` as well. We'd want to support write-only fields which can't be read back - for example composite fields which end up in multiple database columns, or stuff like `Password`, which turns into `PasswordHash`.

**Comment by unclecheese** [comment]
My idea was actually a lot more brute force than that. I was thinking the resolver would have something explicitly hard-coded to ignore `ID`. I see a number of issues with just having it in `excludedFields` by default, all of which you've articulated, so I think we should avoid that entirely.

What makes sense to me is meeting in the middle somewhere, along the lines of `defaultExcludedFields`, where we would have something configurable, but more robust. My instinct is to call it `immutableFields` -- because this condition only applies to the mutation operations (2 or the 3 to be exact) -- and have it defined as a map, so that you don't run into merge issues.

```
SilverStripe\GraphQL\Scaffolding\Scaffolders\DataObjectScaffolder:
  immutableFields:
    ID: true
```

Now someone has to explicitly set that to `false` to end up with writeable IDs.

On your second point, totally correct. I've had my head in this so long, I've lose track of the use cases, and there are scenarios in which fields are writable but not readable. So we do need this applied to `read` operations.

**Comment by chillu** [comment]
`immutableFields` sounds like a good compromise! As long as we throw an exception if you try to add a field to `operations.update/create` which is already listed in `immutableFields`.

**Comment by PapaBearNZ** [comment]
I agree with the immutable fields concept.  And also agree that there needs to be a warning or an outright fatal exception if the mutation query attempts to modify an immutable field.  A create mutation doesn't need to worry about the ID as this will be set during the handling of the query, and an Update should use the ID for identification of the record but has no need to change the id.  Nor does a delete mutation as all it is interested in is identifying the correct object to remove.

Counterpoint: I'm not as keen on the operation-centric approach.  I tend to prefer the map approach for field definition as it will more easily allow extra functionality to be added to the scaffolding in the future.  For now the visibility element might be added, and the immutable setting.  In the future there might be potentially any number of other options allowable.  Thus I think the field-centric approach, whilst it may appear clunkier for now, may offer the best approach for future extensibility.

I also believe the field-centric approach is clearer from an API user's PoV as to exactly what is expected from the scaffolding. Eg.

```
types:
  BlogPost:
    fields:
      ID:
        description: Unique Identifier
        visibility: *
        immutable: true
      Title:
        description: The title field
        visibility: *
      Author:
        description: The author of the post
      Content:
        description: The content of the post
        visibility: [create, update]
    operations:
      read: true
      create: true
      update: true
```

**Comment by chillu** [comment]
I've created a separate issue for nested relationship CRUD: https://github.com/silverstripe/silverstripe-graphql/issues/75

**Comment by chillu** [comment]
@PapaBearNZ Inlining `immutable: true` into individual field definition is defeating the purpose though - it's supposed to be a *global* config default which gets enforced on each mutation. 

I understand your preference for field-centric over operation-centric, but the `immutable: true` isn't a strong point for field-centric.

@unclecheese I could imagine that we want additional configurability on relationship "fields", depending on where the discussion #75 goes. Any relationship inlining will require definition of nested fields as well, right? A field-centric approach would be more natural for this.

**Comment by PapaBearNZ** [comment]
@chillu I was working on the theory that there were global fields that were immutable such as ID but that this could be overridden on a single field case by case basis.  For instance, imagine the hypothetical situation where a dev has classes Alpha, Beta and Gamma defined.  Default config for ID is immutable which is fine for Classes Alpha and Gamma, but for Beta the ID field needs to be mutable for reasons.  If the immutability is only a turn on/turn off globally style of configuration this will open the field to potential lines of abuse or security vulnerability.  If the dev could turn off immutability of a field but only for the specified class then it reduces the scope of vulnerability.

Does that make sense?  Otherwise if you have a situation where you have n classes but only one of them needs a field mutable, and the immutableFields is only applicable globally, you would need to open the mutability of all n classes just to satisfy the use case for the single class.  

By adding the immutable param at a field level, as well as Global you can embrace the best of both worlds.

**Comment by chillu** [comment]
> If the immutability is only a turn on/turn off globally style of configuration this will open the field to potential lines of abuse or security vulnerability

You'd still have to opt-in to allowing the field on a particular type. Unless you use `fields: *` with all the security implications that has anyway (not really best practice).

You can achieve per-field, per-type "immutability" simply by using the field-centric or operation-centric permissions we've outlined on this ticket, no need for a separate concept there. 

```
SilverStripe\GraphQL\Scaffolding\Scaffolders\DataObjectScaffolder:   
  immutableFields:
    ID: true
types:
  BlogPost:
    fields: [ID, Title]
    operations:
      read: true
      create: true # excludes ID implicly
      update:
        fields: [Title] # excludes ID explicitly
        fields: [ID, Title] # throws an exception
```

Ideally we could just define a "default visibility" which YAML config can overwrite, but that gets quite verbose - so I think `immutableFields` is a good compromise.
