### ISSUE TITLE
Add search params to scaffolded READ operations

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#68]
Right now, the scaffolded `READ` operations do not provide any meaningful API for adding `$args`. You can add them, but because the resolver is pre-baked, you can't apply them. You would have to use your own resolver, which defeats the purpose of using scaffolding. 

This would be a great opportunity to use and already established convention such as `SearchContext`.

Possible API:

```
types:
  BlogPost:
    fields: [Title, Content, Author]
    operations:
      read:
        search:
          Title:
            description: Filter the posts by title
          Created:
            description: Filter the posts by their creation date
          Author__Surname:
            description: Search by the author's surname
```

The query would then accept two arguments: `$Filter` and `$Exclude`, each of which would take the above filters.

```
readPosts($Filter, $Exclude) {

}

{
	"Filter": {
	  "Title": { 
	  	"Value": "some search text here",
	  	"Filter": "ExactMatch" // An enum of SearchFilter subclasses
	  },
	  "Created" {
	  	"Value": "2016-01-01",
	  	"Fitler": "GreaterThan"
	  }
	},
	"Exclude": {
		"Author__Surname": {
			"Value": "Smith",
			"Filter": "ExactMatch"
		}
	}
}
```

We could take it a step further to clean up some of the parity with SS `SearchFilter` classes, and alias them.

```
{
	"Filter": {
	  "Title": { 
	  	"Value": "some search text here",
	  	"Comparison": "="
	  },
	  "Created" {
	  	"Value": "2016-01-01",
	  	"Comparison": ">"
	  }
	}
}
```

@chillu has shared some concerns about using `SearchContext` in GraphQL due to complexities like composite filters (e.g. range).

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-graphql/pull/220
