### ISSUE TITLE
Field of type `Int` gets serialized as `null`

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-graphql#73]
A DataObject that has fields defined as `Int` will not serialize the actual field values. Eg.

```php
class Dummy extends \SilverStripe\ORM\DataObject
{
    private static $singular_name = 'Dummy';
    private static $plural_name = 'Dummies';
    
    private static $db = [
        'Number' => 'Int'
    ];
}
```

I've enabled scaffolding using YAML config, like so:

```yml
SilverStripe\GraphQL:
  schema:
    scaffolding:
      types:
        Dummy:
          fields: '*'
          operations:
            read: true
```

Query:

```
query Dummies($limit:Int, $offset:Int) {
  readDummies(limit:$limit, offset:$offset) {
    edges {
      node {
        ID,
        Number,
        Created
      }
    }
  }
}
```

Then returns:

```
{
  "data": {
    "readDummies": {
      "edges": [
        {
          "node": {
            "ID": "1",
            "Number": null,
            "Created": "2017-02-08 17:55:22"
          }
        }
      ]
    }
  }
}
```
Although the Number field contains a number (verified in DB, and ModelAdmin).
